source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'SPNetwork_Example' do
  pod 'Alamofire'
  pod 'SPNetwork', :path => '../'
  target 'SPNetwork_Tests' do
    inherit! :search_paths

    
  end
end
